/*! dvengine — editor avatar (editors/avatar/index.js) · inspector schema for components/avatar · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "avatar",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/avatar",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": -3,
          "y": 0,
          "z": 2
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 5032432,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "height",
        "kind": "number",
        "min": 0,
        "max": 7.2,
        "step": 0.1,
        "options": [],
        "default": 1.8,
        "label": "Height",
        "group": "look"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("avatar", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
