/*! dvengine — editor portal (editors/portal/index.js) · inspector schema for components/portal · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · DeltaVerse-native */
(function (global) {
  'use strict';
  var schema = {
    "type": "portal",
    "upstream": "DeltaVerse-native",
    "native": true,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 2282478,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "height",
        "kind": "number",
        "min": 0,
        "max": 10,
        "step": 0.1,
        "options": [],
        "default": 2.6,
        "label": "Height",
        "group": "look"
      },
      {
        "key": "label",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": "",
        "label": "Label",
        "group": "props"
      },
      {
        "key": "locked",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": false,
        "label": "Locked",
        "group": "props"
      },
      {
        "key": "minRole",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": "",
        "label": "Min Role",
        "group": "props"
      },
      {
        "key": "r",
        "kind": "number",
        "min": 0,
        "max": 6.4,
        "step": 0.1,
        "options": [],
        "default": 1.6,
        "label": "R",
        "group": "props"
      },
      {
        "key": "seed",
        "kind": "int",
        "min": 0,
        "max": 16,
        "step": 1,
        "options": [],
        "default": 3,
        "label": "Seed",
        "group": "props"
      },
      {
        "key": "to",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": "?",
        "label": "To",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("portal", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
