/*! dvengine — editor group (editors/group/index.js) · inspector schema for components/group · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "group",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/group",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": -6,
          "y": 2.5,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 9133302,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "radius",
        "kind": "number",
        "min": 0,
        "max": 6.4,
        "step": 0.1,
        "options": [],
        "default": 1.6,
        "label": "Radius",
        "group": "look"
      },
      {
        "key": "spin",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": true,
        "label": "Spin",
        "group": "motion"
      },
      {
        "key": "count",
        "kind": "int",
        "min": 0,
        "max": 20,
        "step": 1,
        "options": [],
        "default": 5,
        "label": "Count",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("group", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
