/*! dvengine — editor substrate (editors/substrate/index.js) · inspector schema for components/substrate · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · DeltaVerse-native */
(function (global) {
  'use strict';
  var schema = {
    "type": "substrate",
    "upstream": "DeltaVerse-native",
    "native": true,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "height",
        "kind": "number",
        "min": 0,
        "max": 100,
        "step": 0.1,
        "options": [],
        "default": null,
        "label": "Height",
        "group": "look"
      },
      {
        "key": "opacity",
        "kind": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "options": [],
        "default": 1,
        "label": "Opacity",
        "group": "look"
      },
      {
        "key": "preset",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": "gradient",
        "label": "Preset",
        "group": "look"
      },
      {
        "key": "radius",
        "kind": "number",
        "min": 0,
        "max": 100,
        "step": 0.1,
        "options": [],
        "default": null,
        "label": "Radius",
        "group": "look"
      },
      {
        "key": "shape",
        "kind": "enum",
        "min": null,
        "max": null,
        "step": null,
        "options": [
          "sky",
          "floor",
          "ring"
        ],
        "default": "sky",
        "label": "Shape",
        "group": "look"
      },
      {
        "key": "width",
        "kind": "number",
        "min": 0,
        "max": 100,
        "step": 0.1,
        "options": [],
        "default": null,
        "label": "Width",
        "group": "look"
      },
      {
        "key": "fps",
        "kind": "number",
        "min": 0,
        "max": 96,
        "step": 1,
        "options": [],
        "default": 24,
        "label": "Fps",
        "group": "props"
      },
      {
        "key": "seed",
        "kind": "number",
        "min": 0,
        "max": 100,
        "step": 0.1,
        "options": [],
        "default": null,
        "label": "Seed",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("substrate", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
