/*! dvengine — editor postprocessing (editors/postprocessing/index.js) · inspector schema for components/postprocessing · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "postprocessing",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/postprocessing",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "tint",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 2068,
        "label": "Tint",
        "group": "look"
      },
      {
        "key": "grain",
        "kind": "number",
        "min": 0,
        "max": 0.32,
        "step": 0.01,
        "options": [],
        "default": 0.08,
        "label": "Grain",
        "group": "props"
      },
      {
        "key": "vignette",
        "kind": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "options": [],
        "default": 0.6,
        "label": "Vignette",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("postprocessing", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
