/*! dvengine — editor text (editors/text/index.js) · inspector schema for components/text · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "text",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/text",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 5,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "bg",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": null,
        "label": "Bg",
        "group": "look"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": null,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "size",
        "kind": "number",
        "min": 0,
        "max": 16,
        "step": 1,
        "options": [],
        "default": 4,
        "label": "Size",
        "group": "look"
      },
      {
        "key": "billboard",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": true,
        "label": "Billboard",
        "group": "motion"
      },
      {
        "key": "face",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": true,
        "label": "Face",
        "group": "props"
      },
      {
        "key": "text",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": "DeltaVerse",
        "label": "Text",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("text", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
