/*! dvengine — editor camera (editors/camera/index.js) · inspector schema for components/camera · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "camera",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/camera",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 16765286,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "height",
        "kind": "number",
        "min": 0,
        "max": 24,
        "step": 1,
        "options": [],
        "default": 6,
        "label": "Height",
        "group": "look"
      },
      {
        "key": "radius",
        "kind": "number",
        "min": 0,
        "max": 64,
        "step": 1,
        "options": [],
        "default": 16,
        "label": "Radius",
        "group": "look"
      },
      {
        "key": "speed",
        "kind": "number",
        "min": 0,
        "max": 0.48,
        "step": 0.01,
        "options": [],
        "default": 0.12,
        "label": "Speed",
        "group": "motion"
      },
      {
        "key": "drive",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": true,
        "label": "Drive",
        "group": "props"
      },
      {
        "key": "target",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 1.5,
          "z": 0
        },
        "label": "Target",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("camera", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
