/*! dvengine — editor zone (editors/zone/index.js) · inspector schema for components/zone · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · DeltaVerse-native */
(function (global) {
  'use strict';
  var schema = {
    "type": "zone",
    "upstream": "DeltaVerse-native",
    "native": true,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "bounds",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": null,
        "label": "Bounds",
        "group": "props"
      },
      {
        "key": "locked",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": false,
        "label": "Locked",
        "group": "props"
      },
      {
        "key": "minRole",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": "",
        "label": "Min Role",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("zone", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
