/*! dvengine — editor water (editors/water/index.js) · inspector schema for components/water · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "water",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/water",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0.05,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 2792948,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "size",
        "kind": "number",
        "min": 0,
        "max": 80,
        "step": 1,
        "options": [],
        "default": 20,
        "label": "Size",
        "group": "look"
      },
      {
        "key": "deep",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 402490,
        "label": "Deep",
        "group": "props"
      },
      {
        "key": "segments",
        "kind": "int",
        "min": 0,
        "max": 384,
        "step": 1,
        "options": [],
        "default": 96,
        "label": "Segments",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("water", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
