/*! dvengine — editor envmap (editors/envmap/index.js) · inspector schema for components/envmap · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "envmap",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/envmap",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "intensity",
        "kind": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "options": [],
        "default": 1,
        "label": "Intensity",
        "group": "look"
      },
      {
        "key": "background",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": false,
        "label": "Background",
        "group": "props"
      },
      {
        "key": "bottom",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 1054758,
        "label": "Bottom",
        "group": "props"
      },
      {
        "key": "top",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 7310256,
        "label": "Top",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("envmap", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
