/*! dvengine — editor destination (editors/destination/index.js) · inspector schema for components/destination · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "destination",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/destination",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 6,
          "y": 0.05,
          "z": -4
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 8073207,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "height",
        "kind": "number",
        "min": 0,
        "max": 16,
        "step": 1,
        "options": [],
        "default": 4,
        "label": "Height",
        "group": "look"
      },
      {
        "key": "count",
        "kind": "int",
        "min": 0,
        "max": 960,
        "step": 1,
        "options": [],
        "default": 240,
        "label": "Count",
        "group": "props"
      },
      {
        "key": "label",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": "",
        "label": "Label",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("destination", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
