/*! dvengine — editor orb (editors/orb/index.js) · inspector schema for components/orb · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · DeltaVerse-native */
(function (global) {
  'use strict';
  var schema = {
    "type": "orb",
    "upstream": "DeltaVerse-native",
    "native": true,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": "#7fdcff",
        "label": "Color",
        "group": "look"
      },
      {
        "key": "radius",
        "kind": "number",
        "min": 0,
        "max": 0.44,
        "step": 0.01,
        "options": [],
        "default": 0.11,
        "label": "Radius",
        "group": "look"
      },
      {
        "key": "float",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": true,
        "label": "Float",
        "group": "props"
      },
      {
        "key": "glow",
        "kind": "number",
        "min": 0,
        "max": 2.8,
        "step": 0.01,
        "options": [],
        "default": 0.7,
        "label": "Glow",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("orb", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
