/*! dvengine — editor aivatar (editors/aivatar/index.js) · inspector schema for components/aivatar · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · DeltaVerse-native */
(function (global) {
  'use strict';
  var schema = {
    "type": "aivatar",
    "upstream": "DeltaVerse-native",
    "native": true,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "facePreset",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": null,
        "label": "Face Preset",
        "group": "look"
      },
      {
        "key": "tint",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": null,
        "label": "Tint",
        "group": "look"
      },
      {
        "key": "dims",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": null,
        "label": "Dims",
        "group": "props",
        "json": true
      },
      {
        "key": "say",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": null,
        "label": "Say",
        "group": "props",
        "json": true
      },
      {
        "key": "seed",
        "kind": "int",
        "min": 0,
        "max": 16,
        "step": 1,
        "options": [],
        "default": 1,
        "label": "Seed",
        "group": "props"
      },
      {
        "key": "yaw",
        "kind": "number",
        "min": -3.1416,
        "max": 3.1416,
        "step": 0.01,
        "options": [],
        "default": 0,
        "label": "Yaw",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("aivatar", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
