/*! dvengine — editor wave (editors/wave/index.js) · inspector schema for components/wave · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "wave",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/wave",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0.05,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 3856068,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "size",
        "kind": "number",
        "min": 0,
        "max": 160,
        "step": 1,
        "options": [],
        "default": 40,
        "label": "Size",
        "group": "look"
      },
      {
        "key": "amplitude",
        "kind": "number",
        "min": 0,
        "max": 6,
        "step": 0.1,
        "options": [],
        "default": 1.5,
        "label": "Amplitude",
        "group": "props"
      },
      {
        "key": "segments",
        "kind": "int",
        "min": 0,
        "max": 480,
        "step": 1,
        "options": [],
        "default": 120,
        "label": "Segments",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("wave", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
