/*! dvengine — editor vrmanims (editors/vrmanims/index.js) · inspector schema for components/vrmanims · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "vrmanims",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/vrmanims",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 3,
          "y": 0,
          "z": 2
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 16196997,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "speed",
        "kind": "number",
        "min": 0,
        "max": 4,
        "step": 0.1,
        "options": [],
        "default": 1,
        "label": "Speed",
        "group": "motion"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("vrmanims", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
