/*! dvengine — editor navmesh (editors/navmesh/index.js) · inspector schema for components/navmesh · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "navmesh",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/navmesh",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0.02,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 3835647,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "pathColor",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 16711790,
        "label": "Path Color",
        "group": "look"
      },
      {
        "key": "size",
        "kind": "number",
        "min": 0,
        "max": 72,
        "step": 1,
        "options": [],
        "default": 18,
        "label": "Size",
        "group": "look"
      },
      {
        "key": "cells",
        "kind": "number",
        "min": 0,
        "max": 48,
        "step": 1,
        "options": [],
        "default": 12,
        "label": "Cells",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("navmesh", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
