/*! dvengine — editor mesh (editors/mesh/index.js) · inspector schema for components/mesh · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "mesh",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/mesh",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 1.6,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 5099745,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "metalness",
        "kind": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "options": [],
        "default": 0.2,
        "label": "Metalness",
        "group": "look"
      },
      {
        "key": "roughness",
        "kind": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "options": [],
        "default": 0.45,
        "label": "Roughness",
        "group": "look"
      },
      {
        "key": "shape",
        "kind": "enum",
        "min": null,
        "max": null,
        "step": null,
        "options": [
          "box",
          "sphere",
          "torus",
          "cylinder"
        ],
        "default": "box",
        "label": "Shape",
        "group": "look"
      },
      {
        "key": "spin",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": true,
        "label": "Spin",
        "group": "motion"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("mesh", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
