/*! dvengine — editor impact (editors/impact/index.js) · inspector schema for components/impact · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "impact",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/impact",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 16734780,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "size",
        "kind": "number",
        "min": 0,
        "max": 0.56,
        "step": 0.01,
        "options": [],
        "default": 0.14,
        "label": "Size",
        "group": "look"
      },
      {
        "key": "period",
        "kind": "number",
        "min": 0,
        "max": 12,
        "step": 1,
        "options": [],
        "default": 3,
        "label": "Period",
        "group": "motion"
      },
      {
        "key": "sparks",
        "kind": "int",
        "min": 0,
        "max": 320,
        "step": 1,
        "options": [],
        "default": 80,
        "label": "Sparks",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("impact", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
