/*! dvengine — editor bird (editors/bird/index.js) · inspector schema for components/bird · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "bird",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/bird",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 2830136,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "radius",
        "kind": "number",
        "min": 0,
        "max": 32,
        "step": 1,
        "options": [],
        "default": 8,
        "label": "Radius",
        "group": "look"
      },
      {
        "key": "speed",
        "kind": "number",
        "min": 0,
        "max": 2,
        "step": 0.01,
        "options": [],
        "default": 0.5,
        "label": "Speed",
        "group": "motion"
      },
      {
        "key": "count",
        "kind": "int",
        "min": 0,
        "max": 96,
        "step": 1,
        "options": [],
        "default": 24,
        "label": "Count",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("bird", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
