/*! dvengine — editor audio (editors/audio/index.js) · inspector schema for components/audio · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "audio",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/audio",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 2.5,
          "z": -4
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 16756684,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "freq",
        "kind": "number",
        "min": 0,
        "max": 10,
        "step": 0.1,
        "options": [],
        "default": 2.5,
        "label": "Freq",
        "group": "props"
      },
      {
        "key": "range",
        "kind": "number",
        "min": 0,
        "max": 24,
        "step": 1,
        "options": [],
        "default": 6,
        "label": "Range",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("audio", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
