/*! dvengine — editor spline (editors/spline/index.js) · inspector schema for components/spline · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "spline",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/spline",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 8050687,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "radius",
        "kind": "number",
        "min": 0,
        "max": 0.32,
        "step": 0.01,
        "options": [],
        "default": 0.08,
        "label": "Radius",
        "group": "look"
      },
      {
        "key": "speed",
        "kind": "number",
        "min": 0,
        "max": 0.8,
        "step": 0.01,
        "options": [],
        "default": 0.2,
        "label": "Speed",
        "group": "motion"
      },
      {
        "key": "points",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": null,
        "label": "Points",
        "group": "props",
        "json": true
      },
      {
        "key": "segments",
        "kind": "int",
        "min": 0,
        "max": 800,
        "step": 1,
        "options": [],
        "default": 200,
        "label": "Segments",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("spline", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
