/*! dvengine — editor cloud (editors/cloud/index.js) · inspector schema for components/cloud · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "cloud",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/cloud",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": null,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "height",
        "kind": "number",
        "min": 0,
        "max": 56,
        "step": 1,
        "options": [],
        "default": 14,
        "label": "Height",
        "group": "look"
      },
      {
        "key": "spread",
        "kind": "number",
        "min": 0,
        "max": 104,
        "step": 1,
        "options": [],
        "default": 26,
        "label": "Spread",
        "group": "look"
      },
      {
        "key": "drift",
        "kind": "number",
        "min": 0,
        "max": 1.6,
        "step": 0.01,
        "options": [],
        "default": 0.4,
        "label": "Drift",
        "group": "motion"
      },
      {
        "key": "puffs",
        "kind": "int",
        "min": 0,
        "max": 112,
        "step": 1,
        "options": [],
        "default": 28,
        "label": "Puffs",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("cloud", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
