/*! dvengine — editor godray (editors/godray/index.js) · inspector schema for components/godray · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "godray",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/godray",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 16773312,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "opacity",
        "kind": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "options": [],
        "default": 0.14,
        "label": "Opacity",
        "group": "look"
      },
      {
        "key": "length",
        "kind": "number",
        "min": 0,
        "max": 72,
        "step": 1,
        "options": [],
        "default": 18,
        "label": "Length",
        "group": "props"
      },
      {
        "key": "origin",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 16,
          "z": -6
        },
        "label": "Origin",
        "group": "props"
      },
      {
        "key": "rays",
        "kind": "int",
        "min": 0,
        "max": 20,
        "step": 1,
        "options": [],
        "default": 5,
        "label": "Rays",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("godray", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
