/*! dvengine — editor lighting (editors/lighting/index.js) · inspector schema for components/lighting · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "lighting",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/lighting",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "ambientColor",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 4213340,
        "label": "Ambient Color",
        "group": "look"
      },
      {
        "key": "ambientIntensity",
        "kind": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "options": [],
        "default": 0.6,
        "label": "Ambient Intensity",
        "group": "look"
      },
      {
        "key": "intensity",
        "kind": "number",
        "min": 0,
        "max": 5.6,
        "step": 0.1,
        "options": [],
        "default": 1.4,
        "label": "Intensity",
        "group": "look"
      },
      {
        "key": "sunColor",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 16773846,
        "label": "Sun Color",
        "group": "look"
      },
      {
        "key": "animate",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": true,
        "label": "Animate",
        "group": "motion"
      },
      {
        "key": "hemisphere",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": true,
        "label": "Hemisphere",
        "group": "props"
      },
      {
        "key": "sunPosition",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 8,
          "y": 14,
          "z": 6
        },
        "label": "Sun Position",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("lighting", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
