/*! dvengine — editor participant (editors/participant/index.js) · inspector schema for components/participant · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · DeltaVerse-native */
(function (global) {
  'use strict';
  var schema = {
    "type": "participant",
    "upstream": "DeltaVerse-native",
    "native": true,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 4
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "height",
        "kind": "number",
        "min": 0,
        "max": 100,
        "step": 0.1,
        "options": [],
        "default": null,
        "label": "Height",
        "group": "look"
      },
      {
        "key": "tint",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 5032432,
        "label": "Tint",
        "group": "look"
      },
      {
        "key": "speed",
        "kind": "number",
        "min": 0,
        "max": 8.8,
        "step": 0.1,
        "options": [],
        "default": 2.2,
        "label": "Speed",
        "group": "motion"
      },
      {
        "key": "run",
        "kind": "int",
        "min": 0,
        "max": 18,
        "step": 1,
        "options": [],
        "default": 4.4,
        "label": "Run",
        "group": "props"
      },
      {
        "key": "seed",
        "kind": "int",
        "min": 0,
        "max": 44,
        "step": 1,
        "options": [],
        "default": 11,
        "label": "Seed",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("participant", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
