/*! dvengine — editor instancedmesh (editors/instancedmesh/index.js) · inspector schema for components/instancedmesh · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "instancedmesh",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/instancedmesh",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 5099745,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "shape",
        "kind": "enum",
        "min": null,
        "max": null,
        "step": null,
        "options": [
          "sphere"
        ],
        "default": "sphere",
        "label": "Shape",
        "group": "look"
      },
      {
        "key": "animate",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": true,
        "label": "Animate",
        "group": "motion"
      },
      {
        "key": "cols",
        "kind": "int",
        "min": 0,
        "max": 48,
        "step": 1,
        "options": [],
        "default": 12,
        "label": "Cols",
        "group": "props"
      },
      {
        "key": "gap",
        "kind": "number",
        "min": 0,
        "max": 4.4,
        "step": 0.1,
        "options": [],
        "default": 1.1,
        "label": "Gap",
        "group": "props"
      },
      {
        "key": "rows",
        "kind": "int",
        "min": 0,
        "max": 48,
        "step": 1,
        "options": [],
        "default": 12,
        "label": "Rows",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("instancedmesh", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
