/*! dvengine — editor quarks (editors/quarks/index.js) · inspector schema for components/quarks · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "quarks",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/quarks",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 16761434,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "size",
        "kind": "number",
        "min": 0,
        "max": 0.72,
        "step": 0.01,
        "options": [],
        "default": 0.18,
        "label": "Size",
        "group": "look"
      },
      {
        "key": "spread",
        "kind": "number",
        "min": 0,
        "max": 8,
        "step": 1,
        "options": [],
        "default": 2,
        "label": "Spread",
        "group": "look"
      },
      {
        "key": "life",
        "kind": "number",
        "min": 0,
        "max": 6.4,
        "step": 0.1,
        "options": [],
        "default": 1.6,
        "label": "Life",
        "group": "props"
      },
      {
        "key": "rate",
        "kind": "int",
        "min": 0,
        "max": 800,
        "step": 1,
        "options": [],
        "default": 200,
        "label": "Rate",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("quarks", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
