/*! dvengine — editor terrain (editors/terrain/index.js) · inspector schema for components/terrain · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "terrain",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/terrain",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "height",
        "kind": "number",
        "min": 0,
        "max": 12,
        "step": 1,
        "options": [],
        "default": 3,
        "label": "Height",
        "group": "look"
      },
      {
        "key": "size",
        "kind": "number",
        "min": 0,
        "max": 160,
        "step": 1,
        "options": [],
        "default": 40,
        "label": "Size",
        "group": "look"
      },
      {
        "key": "flat",
        "kind": "bool",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": false,
        "label": "Flat",
        "group": "props"
      },
      {
        "key": "high",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 15262934,
        "label": "High",
        "group": "props"
      },
      {
        "key": "low",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 2179111,
        "label": "Low",
        "group": "props"
      },
      {
        "key": "mid",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 7043898,
        "label": "Mid",
        "group": "props"
      },
      {
        "key": "segments",
        "kind": "int",
        "min": 0,
        "max": 384,
        "step": 1,
        "options": [],
        "default": 96,
        "label": "Segments",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("terrain", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
