/*! dvengine — editor thot-memory (editors/thot-memory/index.js) · inspector schema for components/thot-memory · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · DeltaVerse-native */
(function (global) {
  'use strict';
  var schema = {
    "type": "thot-memory",
    "upstream": "DeltaVerse-native",
    "native": true,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 2.2,
          "z": -6
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "size",
        "kind": "number",
        "min": 0,
        "max": 8.8,
        "step": 0.1,
        "options": [],
        "default": 2.2,
        "label": "Size",
        "group": "look"
      },
      {
        "key": "depth",
        "kind": "number",
        "min": 0,
        "max": 16,
        "step": 1,
        "options": [],
        "default": 4,
        "label": "Depth",
        "group": "props"
      },
      {
        "key": "fps",
        "kind": "number",
        "min": 0,
        "max": 48,
        "step": 1,
        "options": [],
        "default": 12,
        "label": "Fps",
        "group": "props"
      },
      {
        "key": "label",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": "",
        "label": "Label",
        "group": "props"
      },
      {
        "key": "nodes",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": null,
        "label": "Nodes",
        "group": "props",
        "json": true
      },
      {
        "key": "root",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": "0x0",
        "label": "Root",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("thot-memory", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
