/*! dvengine — editor background (editors/background/index.js) · inspector schema for components/background · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "background",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/background",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 658968,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "bottom",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 329485,
        "label": "Bottom",
        "group": "props"
      },
      {
        "key": "top",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 1450042,
        "label": "Top",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("background", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
