/*! dvengine — editor rain (editors/rain/index.js) · inspector schema for components/rain · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "rain",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/rain",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "area",
        "kind": "number",
        "min": 0,
        "max": 80,
        "step": 1,
        "options": [],
        "default": 20,
        "label": "Area",
        "group": "look"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 11455462,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "size",
        "kind": "number",
        "min": 0,
        "max": 0.28,
        "step": 0.01,
        "options": [],
        "default": 0.07,
        "label": "Size",
        "group": "look"
      },
      {
        "key": "speed",
        "kind": "number",
        "min": 0,
        "max": 48,
        "step": 1,
        "options": [],
        "default": 12,
        "label": "Speed",
        "group": "motion"
      },
      {
        "key": "count",
        "kind": "int",
        "min": 0,
        "max": 8000,
        "step": 1,
        "options": [],
        "default": 2000,
        "label": "Count",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("rain", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
