/*! dvengine — editor sceptre (editors/sceptre/index.js) · inspector schema for components/sceptre · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · DeltaVerse-native */
(function (global) {
  'use strict';
  var schema = {
    "type": "sceptre",
    "upstream": "DeltaVerse-native",
    "native": true,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 2829634,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "tint",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": "#f5c451",
        "label": "Tint",
        "group": "look"
      },
      {
        "key": "glow",
        "kind": "number",
        "min": 0,
        "max": 3.2,
        "step": 0.01,
        "options": [],
        "default": 0.8,
        "label": "Glow",
        "group": "props"
      },
      {
        "key": "length",
        "kind": "number",
        "min": 0,
        "max": 3.6,
        "step": 0.01,
        "options": [],
        "default": 0.9,
        "label": "Length",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("sceptre", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
