/*! dvengine — editor particles (editors/particles/index.js) · inspector schema for components/particles · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "particles",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/particles",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "area",
        "kind": "number",
        "min": 0,
        "max": 56,
        "step": 1,
        "options": [],
        "default": 14,
        "label": "Area",
        "group": "look"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 10480127,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "size",
        "kind": "number",
        "min": 0,
        "max": 0.48,
        "step": 0.01,
        "options": [],
        "default": 0.12,
        "label": "Size",
        "group": "look"
      },
      {
        "key": "speed",
        "kind": "number",
        "min": 0,
        "max": 4,
        "step": 0.1,
        "options": [],
        "default": 1,
        "label": "Speed",
        "group": "motion"
      },
      {
        "key": "count",
        "kind": "int",
        "min": 0,
        "max": 4800,
        "step": 1,
        "options": [],
        "default": 1200,
        "label": "Count",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("particles", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
