/*! dvengine — editor piece (editors/piece/index.js) · inspector schema for components/piece · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · DeltaVerse-native */
(function (global) {
  'use strict';
  var schema = {
    "type": "piece",
    "upstream": "DeltaVerse-native",
    "native": true,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "frameColor",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 1711915,
        "label": "Frame Color",
        "group": "look"
      },
      {
        "key": "size",
        "kind": "number",
        "min": 0,
        "max": 6.8,
        "step": 0.1,
        "options": [],
        "default": 1.7,
        "label": "Size",
        "group": "look"
      },
      {
        "key": "nft",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": null,
        "label": "Nft",
        "group": "props",
        "json": true
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("piece", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
