/*! dvengine — editor remote-participant (editors/remote-participant/index.js) · inspector schema for components/remote-participant · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · DeltaVerse-native */
(function (global) {
  'use strict';
  var schema = {
    "type": "remote-participant",
    "upstream": "DeltaVerse-native",
    "native": true,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "avatar",
        "kind": "string",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {},
        "label": "Avatar",
        "group": "props",
        "json": true
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("remote-participant", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
