/*! dvengine — editor fog (editors/fog/index.js) · inspector schema for components/fog · GENERATED by scripts/gen-editors.mjs · (c) 2026 BANKON / PYTHAI · dddcyborgd · MIT · upstream © oncyberio (awe, MIT) where derived */
(function (global) {
  'use strict';
  var schema = {
    "type": "fog",
    "upstream": "https://github.com/oncyberio/awe/tree/main/packages/engine/src/space/components/fog",
    "native": false,
    "rows": [
      {
        "key": "position",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Position",
        "group": "transform"
      },
      {
        "key": "rotation",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 0,
          "y": 0,
          "z": 0
        },
        "label": "Rotation",
        "group": "transform"
      },
      {
        "key": "scale",
        "kind": "vec3",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": {
          "x": 1,
          "y": 1,
          "z": 1
        },
        "label": "Scale",
        "group": "transform"
      },
      {
        "key": "color",
        "kind": "color",
        "min": null,
        "max": null,
        "step": null,
        "options": [],
        "default": 658968,
        "label": "Color",
        "group": "look"
      },
      {
        "key": "density",
        "kind": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "options": [],
        "default": 0.012,
        "label": "Density",
        "group": "props"
      },
      {
        "key": "far",
        "kind": "number",
        "min": 0,
        "max": 240,
        "step": 1,
        "options": [],
        "default": 60,
        "label": "Far",
        "group": "props"
      },
      {
        "key": "near",
        "kind": "number",
        "min": 0,
        "max": 32,
        "step": 1,
        "options": [],
        "default": 8,
        "label": "Near",
        "group": "props"
      }
    ]
  };
  if (global.DVEditors) global.DVEditors.register("fog", schema);
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
